version: '3.8'

services:
  web:
    build: .
    command: python -m flask run -h 0.0.0.0
    volumes:
      - ./devided_project:/Users/user/PycharmProjects/devided_project
    ports:
      - 5005:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=unilime

volumes:
  postgres_data:
